services:
  nextjs-app:
    platform: linux/amd64
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    restart: unless-stopped
